name: text_summarize_with_ai
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  sqflite: ^2.3.0
  path: ^1.8.3
  google_fonts: ^6.3.3
  cupertino_icons: ^1.0.8
  lottie: ^3.3.2
  share_plus: ^12.0.1
  introduction_screen: ^4.0.0
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/ai_animation.json

flutter_native_splash:
  color: "#673AB7"
  
  android_12:
    color: "#673AB7"
    icon_background_color: "#673AB7"